<div class="text-center" ng-show="totalPages() > 1">
	<ul class="pagination">
		<li class="arrow" ng-class="{disabled: currentPage() <= 1}" ng-click="loadPage(currentPage()-1)"><a href="javascript:void(null)">&laquo;</a></li>
		<li ng-repeat="page in pagesBack" ng-click="loadPage(page.number)"><a href="javascript:void(null)">{{page.number}}</a></li>
		<li class="active"><a href="javascript:void(null)">{{currentPage()}}</a></li>
		<li ng-repeat="page in pagesForward" ng-click="loadPage(page.number)"><a href="javascript:void(null)">{{page.number}}</a></li>
		<li class="arrow" ng-class="{disabled: currentPage() >= totalPages()}" ng-click="loadPage(currentPage()+1)"><a href="javascript:void(null)">&raquo;</a></li>
	</ul>
</div>