<?php
/* @var $form \Zend\Form\Form */
$form = $this->form;
$form->setAttributes(array(
	'role' => 'form',
	'data-role' => 'form',
	'class' => 'form-horizontal',
	'action' => $this->url,
));
$form->setAttribute('action', $this->url);
$form->prepare();
?><form role="form" class="form-horizontal"><?php
/* @var $element \Zend\Form\Element */
foreach ($form as $element) {
	?>
		<div class="form-group<?php echo $this->formElementErrors($element) ? ' has-error' : '' ?>">
			<label class="col-lg-2 control-label"><?php echo $element->getLabel(); ?></label>
			<div class="col-lg-10">
				<?php
				$class = $element->getAttribute('class');
				$element->setAttribute('class', $class . ' form-control');
				echo $this->formElement($element);
				if ($this->formElementErrors($element)) {
					?>
					<span class="help-block"><?php echo $this->formElementErrors($element) ?></span>
				<?php } ?>
			</div>
		</div>

		<?php
	}
	?>
</form>
