<?php

use Application\Controller\UserController as ManageUserController;

$this->inlineScript()->appendFile('/js/controllers-ng/user/manage-ctrl.js')
		->appendFile('/js/file-upload/jquery.iframe-transport.js')
		->appendFile('/js/file-upload/jquery.ui.widget.js')
		->appendFile('/js/file-upload/jquery.fileupload.js');
?>
<div ng-controller="ManageUserCtrl" <?php echo $this->initNg('init', array('user' => $this->entity, 'roleMap' => $this->inviteRoles), true, true); ?>>
	<h1>Create {{getRoleDisplayName()}}</h1>
	<div class="row">
		<div class="col-lg-12">
			<a ng-href="<?php echo $this->url(ManageUserController::ROUTE_USER_MANAGE,array('user' => 0)) ?>" class="btn btn-info pull-right">Return to Users</a>
		</div>
	</div>
	<div class="row">
		<ul class="nav nav-tabs">
			<li ng-class="{active:!bulkUpload}"><a href="javascript:void(null)" ng-click="bulkUpload = false">Single User</a></li>
			<li ng-class="{active: bulkUpload}"><a href="javascript:void(null)" ng-click="bulkUpload = true">Upload File</a></li>
		</ul>
	</div>
	<div class='row'>
		<div ng-hide="bulkUpload">
			<?php
			echo $this->partial('form/form.phtml', array(
				'form' => $this->form,
				'url' => $this->url(ManageUserController::ROUTE_USER_MANAGE, array('action' => 'create')),
				'elements' => array('email', 'username')
			));
			?>
		</div>
		<div ng-show="bulkUpload" class="row">
			<div ng-show="!uploading">
				<input ng-disabled="uploading" type="file" name="upload_invites" angular-upload='{"batch":1}' />
			</div>
			<div ng-show="uploading">
				<div class="progress progress-striped active progress-bar-success">
					<div class="progress-bar"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
						<span class="sr-only">Uploading...</span>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>