<?php

use Application\Controller\UserController;
?>
<h1>Forgot Password</h1>
<form action="<?php echo $this->url(UserController::ROUTE_USER_MANAGE, array('action' => 'forgot')) ?>" method="POST" class="form-horizontal" role="form">
	<div class="form-group">
		<label for="inputEmail1" class="col-lg-2 control-label">Email</label>
		<div class="col-lg-10">
			<input type="email" name="email" class="form-control" id="inputEmail1" placeholder="Email">
		</div>
	</div>
	<div class="form-group">
		<div class="col-lg-offset-2 col-lg-10">
			<button type="submit" class="btn btn-default">Reset Password</button>
		</div>
	</div>
</form>