<?php

use Application\Controller\UserController;
use Application\View\Helper\PageNg;
?>

<h1>Manage Users</h1>
<?php
echo $this->pageNg(array(
	PageNg::OPTION_DATA => $this->page,
	PageNg::OPTION_ROW_HEADINGS => array(
		'<th>ID</th>', '<th>Email</th>', '<th>User Name</th>'
	),
	PageNg::OPTION_ROW_TMP => '<td>{{entry.id}}</td><td><a ng-href="' . $this->url(UserController::ROUTE_USER_MANAGE, array('action' => 'manage')) . '/{{entry.id}}">{{entry.email}}</a></td><td>{{entry.username}}</td>',
));
?>